### ISSUE TITLE
forum

### ISSUE THREAD

**Issue by codersuntited** [GLITCHER-Templates/GLITCHER-Templates.github.io#2]
@LankyBox01 want admin perms!

**Comment by LankyBox01** [comment]
https://github.com/GLITCHER-Templates/Forums < I told you to make the forum here.

Anyways, just give me the password to the admin user

**Comment by codersuntited** [comment]
@LankyBox01 if you have a custom domain you can use that with free flarum

**Comment by codersuntited** [comment]
@LankyBox01 make a account and I will give u admin

**Comment by LankyBox01** [comment]
really? Huh, can you register glitcher.tk on http://www.dot.tk/?

**Comment by LankyBox01** [comment]
> @LankyBox01 make a account and I will give u admin

But i started this, i have to be the owner, and you just be a normal admin

**Comment by codersuntited** [comment]
@LankyBox01 its doesn't work for me. Its says that freedom cant verify me as human

**Comment by LankyBox01** [comment]
> @LankyBox01 its doesn't work for me. Its says that freedom cant verify me as human

it's different on dot.tk
try it pls

**Comment by codersuntited** [comment]
I tried multiple times @LankyBox01

**Comment by codersuntited** [comment]
@LankyBox01 

> https://github.com/GLITCHER-Templates/Forums < I told you to make the forum here.
> really? Huh, can you register glitcher.tk on http://www.dot.tk/?
Well I cant do everything for you. You are the owner of the group.
you should be doing the main things

**Comment by LankyBox01** [comment]
> I tried multiple times @LankyBox01

"if you don't succeed try again"
-Ghandi

**Comment by codersuntited** [comment]
@LankyBox01 off topic: do you live in India ?

**Comment by codersuntited** [comment]
idk why I am asking

**Comment by LankyBox01** [comment]
No i live in romania, and i'm turkish XD

**Comment by codersuntited** [comment]
@LankyBox01 
since your the owner of the group you should do every thing.

**Comment by LankyBox01** [comment]
> @LankyBox01
> since your the owner of the group you should do every thing.

not **every** thing, that's why collaborators exist.

Give me the password to the forum admin

**Comment by LankyBox01** [comment]
and make another account, cuz i can't demote you to moderator

**Comment by codersuntited** [comment]
> But i started this, i have to be the owner, and you just be a normal admin

But I created the forum.

**Comment by LankyBox01** [comment]
> > But i started this, i have to be the owner, and you just be a normal admin
> 
> But I created the forum.

Make another account

**Comment by codersuntited** [comment]
@LankyBox01 why do I have to give the password? Its my personal password.

**Comment by LankyBox01** [comment]
change it to something else

**Comment by codersuntited** [comment]
@LankyBox01 why dont you create a new account. You will be full admin, so you will have full access

**Comment by codersuntited** [comment]
@LankyBox01 anyways if you want to be the owner account why dont your create the forum on freeflarum right?

**Comment by LankyBox01** [comment]
no, the owner who created the forum actually has more access (like deleting the forum and other stuff)

**Comment by LankyBox01** [comment]
CHANGE IT TO "LankyMuffin23"

**Comment by codersuntited** [comment]
@LankyBox01 how about I delete the forum and you make it

**Comment by codersuntited** [comment]
@LankyBox01 and I dont want you to use my email for your account

**Comment by LankyBox01** [comment]
> anyways if you want to be the owner account why dont your create the forum on freeflarum right?

Because you already took the glitcher name

**Comment by codersuntited** [comment]
@LankyBox01 I will delete it so you can have it

**Comment by LankyBox01** [comment]
> @LankyBox01 and I dont want you to use my email for your account

i can't see your email, ugh just change it to "blahblah@blahblah.com"

**Comment by LankyBox01** [comment]
c'mon!!!

**Comment by codersuntited** [comment]
# @LankyBox01 im doing it

**Comment by LankyBox01** [comment]
don't delete it

**Comment by codersuntited** [comment]
why not. its better if you have full admin access

**Comment by codersuntited** [comment]
@LankyBox01 fine I will give u the pwd. BUT NOT OVER THE ISSUES. PEOPLE CAN SEE TEHM

**Comment by LankyBox01** [comment]
where then?

**Comment by LankyBox01** [comment]
DM me on glitch

**Comment by codersuntited** [comment]
@LankyBox01 I dont have glitch forum account

**Comment by LankyBox01** [comment]
then where?

**Comment by codersuntited** [comment]
@LankyBox01 make a account on the forum and I will dm u there

**Comment by LankyBox01** [comment]
k

**Comment by LankyBox01** [comment]
delete the forum!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!1

**Comment by codersuntited** [comment]
@LankyBox01 okay but why?????????????????

**Comment by codersuntited** [comment]
@LankyBox01 Tell Me WHYYYYYYYYYYYYYYYYYYYYY @LankyBox01

**Comment by LankyBox01** [comment]
> @LankyBox01 Tell Me WHYYYYYYYYYYYYYYYYYYYYY @LankyBox01

just do it

**Comment by codersuntited** [comment]
@LankyBox01 why?????????????????????????

**Comment by codersuntited** [comment]
@LankyBox01 yyyyyyy????????

**Comment by LankyBox01** [comment]
do it, please, i own the name

**Comment by codersuntited** [comment]
@LankyBox01 but why? btw you dont own the name unless you copyright it.

**Comment by codersuntited** [comment]
@LankyBox01 okay fine!

**Comment by codersuntited** [comment]
@LankyBox01 **DONE!**

**Comment by LankyBox01** [comment]
> @LankyBox01 **DONE!**

no need to be rude

**Comment by codersuntited** [comment]
@LankyBox01 not being rude in any ways
